# action.yml
name: 'Armory Aquasec Image Scan'
description: 'Scan a Dockerimage using Aquasec'
inputs:
  username:
    description: Aquasec Username
    required: true
  password:
    description: Aquasec Password
    required: true
  url:
    description: Aquasec URL
    required: true
  image:
    description: Image to be scanned
    required: true
  registry:
    description: Registry of Image
    required: true
  useCloudAuth:
    description: Uses auth against api.cloudsploit.com for cloud aquasec auth.  For users of cloud.aquasec.com.  ONLY used when set to true
    required: false
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -username
    - ${{ inputs.username }}
    - -password
    - ${{ inputs.password }}
    - -url
    - ${{ inputs.url }}
    - -registry
    - ${{ inputs.registry }}
    - -image
    - ${{ inputs.image }}
    - -useCloudAuth
    - ${{ inputs.useCloudAuth }}
